#!/usr/bin/env python3
"""Regenerate a layout's key manifest from its key-layout config.

A layout config states which characters that layout offers. The manifest is a
readable view of it, generated by this script — never hand-edited. Each layout
names its own manifest in the config's "generates" field, so this script writes
wherever the config points rather than to one fixed path. Run it after any
change to a config:

    python scripts/generate-key-manifest.py
    python scripts/generate-key-manifest.py --config resources/some-variant.json

Pass --check to verify the manifest on disk matches what the config would
generate, without writing (exit 1 if it has drifted).
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = ROOT / "resources" / "key-layout.json"


def header(config, config_path):
    return (
        "<!-- GENERATED FILE — DO NOT HAND-EDIT.\n"
        "     Layout: {} ({}).\n"
        "     Generated from {} by scripts/generate-key-manifest.py.\n"
        "     Edit the JSON and re-run the script; any edit made here will be "
        "overwritten. -->".format(config["name"], config["id"], config_path)
    )

EMPTY = "·"


def code(char):
    """Render one character as inline markdown code, handling the backtick."""
    if char == "`":
        return "`` ` ``"
    return "`{}`".format(char)


def col_range(row):
    lo, hi = row["colMin"], row["colMax"]
    return "cols {}–{}".format(lo, hi)


def render_row(panel, row):
    """Render one row as a manifest bullet: its keys in column order."""
    by_col = {k["col"]: k for k in panel["keys"] if k["row"] == row["index"]}
    empty_cols = {
        s["col"] for s in panel.get("emptySlots", []) if s["row"] == row["index"]
    }
    cells = []
    for col in range(row["colMin"], row["colMax"] + 1):
        if col in by_col:
            cells.append(code(by_col[col]["label"]))
        elif col in empty_cols:
            cells.append(code(EMPTY))
        else:
            raise SystemExit(
                "Panel {} row {} col {} is neither a key nor a declared empty slot. "
                "Every slot inside a row's declared bounds must be one or the other.".format(
                    panel["name"], row["index"], col
                )
            )
    line = "- **row{}** ({}): {}".format(row["index"], col_range(row), " ".join(cells))
    if row.get("note"):
        line += " — {}".format(row["note"])
    return line


def render_non_output(panel):
    """Name the panel's keys that don't insert their own label."""
    specials = [k for k in panel["keys"] if k["action"] != "insert"]
    if not specials:
        return None
    described = []
    for k in specials:
        word = {
            "backspace": "backspace",
            "shift": "shift",
            "enter": "enter (outputs a newline)",
            "cursorLeft": "cursor-left",
            "cursorRight": "cursor-right",
        }.get(k["action"], k["action"])
        described.append("{} {}".format(code(k["label"]), word))
    return "Non-output keys on this panel: {}.".format(", ".join(described))


def render_panel(panel):
    out = ["## Panel {} — {}".format(panel["index"], panel["name"]), ""]
    if panel.get("description"):
        out += [panel["description"], ""]
    if panel.get("emptySlots"):
        out += ["{} marks an intentionally empty slot.".format(code(EMPTY)), ""]
    for row in panel["rows"]:
        out.append(render_row(panel, row))
    out.append("")
    non_output = render_non_output(panel)
    if non_output:
        out += [non_output, ""]
    if panel.get("footnote"):
        out += [panel["footnote"], ""]
    if panel.get("emptySlots"):
        out += ["Why each empty slot is empty:", ""]
        for slot in panel["emptySlots"]:
            out.append(
                "- row{} col{} — {}".format(slot["row"], slot["col"], slot["note"])
            )
        out.append("")
    return out


def render_long_press(config, kinds, title, alphabetical=False):
    rows = []
    for panel in config["panels"]:
        for key in panel["keys"]:
            if key.get("longPress") and key["kind"] in kinds:
                label = key["output"] if key["kind"] == "letter" else key["label"]
                rows.append(
                    "- {} → {}".format(
                        label if key["kind"] == "letter" else code(label),
                        " ".join(code(a) for a in key["longPress"]),
                    )
                )
    if not rows:
        return []
    if alphabetical:
        rows.sort()
    return ["## Long-press map — {}".format(title), ""] + rows + [""]


def build(config, config_path):
    out = [
        header(config, config_path),
        "",
        "# Key manifest — {}".format(config["name"]),
        "",
        "This document is a readable view of one Hexboard layout's key inventory: which "
        "characters this layout offers, which panel they live on, and where on that panel "
        "they sit. The layout is {}, identified as `{}`{}. It is generated from `{}`, which "
        "is the actual source of truth. Edit the JSON, then re-run "
        "`scripts/generate-key-manifest.py`.".format(
            config["name"],
            config["id"],
            ", and is the default layout the app ships with"
            if config.get("isDefault")
            else "",
            config_path,
        ),
        "",
        "Its scope is the three letter and symbol panels. The emoji panels reached by "
        "vertical swipe down are system-supplied content rather than a hand-curated "
        "inventory, so they are deliberately outside this manifest and the four rules "
        "below do not apply to them — their absence here is correct, not a gap.",
        "",
        "Geometry is deliberately not here and not in the config: zag offsets, circle radius, "
        "touch-target sizing, uppercase scaling and nearest-centre hit-testing live in Kotlin, "
        "because they are the perceptual claim SPEC calls inviolable. A variant may change "
        "which characters you get, never how it feels to aim at them.",
        "",
        "## The four inviolable rules",
        "",
    ]
    for i, rule in enumerate(config["manifestRules"], start=1):
        head, _, tail = rule.partition(". ")
        out.append("{}. **{}.** {}".format(i, head, tail))
    out += ["", config["rule1Note"], "", "## Files that do not read this config", ""]
    out.append(
        "These hold their own copies of key data by design. They are not generated from "
        "the config and are not kept in step with it automatically."
    )
    out.append("")
    for item in config["nonConsumers"]:
        out.append("- {}".format(item))
    out.append("")
    for panel in config["panels"]:
        out += render_panel(panel)
    out += render_long_press(config, {"letter"}, "letters", alphabetical=True)
    out += render_long_press(config, {"punctuation", "symbol", "space"}, "punctuation")
    return "\n".join(out).rstrip("\n") + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the manifest matches the config; write nothing",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help="the layout config to generate from (default: resources/key-layout.json)",
    )
    args = parser.parse_args()

    config_path = args.config.resolve()
    config = json.loads(config_path.read_text(encoding="utf-8"))

    try:
        config_rel = config_path.relative_to(ROOT).as_posix()
    except ValueError:
        config_rel = config_path.as_posix()

    manifest = ROOT / config["generates"]
    manifest_rel = config["generates"]
    generated = build(config, config_rel)

    if args.check:
        current = manifest.read_text(encoding="utf-8") if manifest.exists() else ""
        if current != generated:
            rerun = "python scripts/generate-key-manifest.py"
            if config_path != DEFAULT_CONFIG:
                rerun += " --config {}".format(config_rel)
            print(
                "{} is out of date with {}. Run: {}".format(
                    manifest_rel, config_rel, rerun
                ),
                file=sys.stderr,
            )
            return 1
        print("{} is up to date.".format(manifest_rel))
        return 0

    manifest.write_text(generated, encoding="utf-8", newline="\n")
    print("Wrote {}".format(manifest_rel))
    return 0


if __name__ == "__main__":
    sys.exit(main())
