#!/usr/bin/env python3
"""Regenerate resources/key-manifest.md from resources/key-layout.json.

key-layout.json is the single source of truth for Hexboard's key inventory.
The manifest is a readable view of it, generated by this script — never
hand-edited. Run this after any change to the config:

    python scripts/generate-key-manifest.py

Pass --check to verify the manifest on disk matches what the config would
generate, without writing (exit 1 if it has drifted).
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "resources" / "key-layout.json"
MANIFEST = ROOT / "resources" / "key-manifest.md"

HEADER = (
    "<!-- GENERATED FILE — DO NOT HAND-EDIT.\n"
    "     Generated from resources/key-layout.json by scripts/generate-key-manifest.py.\n"
    "     Edit the JSON and re-run the script; any edit made here will be overwritten. -->"
)

EMPTY = "·"


def code(char):
    """Render one character as inline markdown code, handling the backtick."""
    if char == "`":
        return "`` ` ``"
    return "`{}`".format(char)


def col_range(row):
    lo, hi = row["colMin"], row["colMax"]
    return "cols {}–{}".format(lo, hi)


def render_row(panel, row):
    """Render one row as a manifest bullet: its keys in column order."""
    by_col = {k["col"]: k for k in panel["keys"] if k["row"] == row["index"]}
    empty_cols = {
        s["col"] for s in panel.get("emptySlots", []) if s["row"] == row["index"]
    }
    cells = []
    for col in range(row["colMin"], row["colMax"] + 1):
        if col in by_col:
            cells.append(code(by_col[col]["label"]))
        elif col in empty_cols:
            cells.append(code(EMPTY))
        else:
            raise SystemExit(
                "Panel {} row {} col {} is neither a key nor a declared empty slot. "
                "Every slot inside a row's declared bounds must be one or the other.".format(
                    panel["name"], row["index"], col
                )
            )
    line = "- **row{}** ({}): {}".format(row["index"], col_range(row), " ".join(cells))
    if row.get("note"):
        line += " — {}".format(row["note"])
    return line


def render_non_output(panel):
    """Name the panel's keys that don't insert their own label."""
    specials = [k for k in panel["keys"] if k["action"] != "insert"]
    if not specials:
        return None
    described = []
    for k in specials:
        word = {
            "backspace": "backspace",
            "shift": "shift",
            "enter": "enter (outputs a newline)",
            "cursorLeft": "cursor-left",
            "cursorRight": "cursor-right",
        }.get(k["action"], k["action"])
        described.append("{} {}".format(code(k["label"]), word))
    return "Non-output keys on this panel: {}.".format(", ".join(described))


def render_panel(panel):
    out = ["## Panel {} — {}".format(panel["index"], panel["name"]), ""]
    if panel.get("description"):
        out += [panel["description"], ""]
    if panel.get("emptySlots"):
        out += ["{} marks an intentionally empty slot.".format(code(EMPTY)), ""]
    for row in panel["rows"]:
        out.append(render_row(panel, row))
    out.append("")
    non_output = render_non_output(panel)
    if non_output:
        out += [non_output, ""]
    if panel.get("footnote"):
        out += [panel["footnote"], ""]
    if panel.get("emptySlots"):
        out += ["Why each empty slot is empty:", ""]
        for slot in panel["emptySlots"]:
            out.append(
                "- row{} col{} — {}".format(slot["row"], slot["col"], slot["note"])
            )
        out.append("")
    return out


def render_long_press(config, kinds, title, alphabetical=False):
    rows = []
    for panel in config["panels"]:
        for key in panel["keys"]:
            if key.get("longPress") and key["kind"] in kinds:
                label = key["output"] if key["kind"] == "letter" else key["label"]
                rows.append(
                    "- {} → {}".format(
                        label if key["kind"] == "letter" else code(label),
                        " ".join(code(a) for a in key["longPress"]),
                    )
                )
    if not rows:
        return []
    if alphabetical:
        rows.sort()
    return ["## Long-press map — {}".format(title), ""] + rows + [""]


def build(config):
    out = [
        HEADER,
        "",
        "# Canonical key manifest",
        "",
        "This document is a readable view of Hexboard's key inventory: which characters "
        "exist, which panel they live on, and where on that panel they sit. It is generated "
        "from `resources/key-layout.json`, which is the actual source of truth. Edit the "
        "JSON, then re-run `scripts/generate-key-manifest.py`.",
        "",
        "Its scope is the three letter and symbol panels. The emoji panels reached by "
        "vertical swipe down are system-supplied content rather than a hand-curated "
        "inventory, so they are deliberately outside this manifest and the four rules "
        "below do not apply to them — their absence here is correct, not a gap.",
        "",
        "Geometry is deliberately not here and not in the config: zag offsets, circle radius, "
        "touch-target sizing, uppercase scaling and nearest-centre hit-testing live in Kotlin, "
        "because they are the perceptual claim SPEC calls inviolable. A variant may change "
        "which characters you get, never how it feels to aim at them.",
        "",
        "## The four inviolable rules",
        "",
    ]
    for i, rule in enumerate(config["manifestRules"], start=1):
        head, _, tail = rule.partition(". ")
        out.append("{}. **{}.** {}".format(i, head, tail))
    out += ["", config["rule1Note"], "", "## Files that do not read this config", ""]
    out.append(
        "These hold their own copies of key data by design. They are not generated from "
        "the config and are not kept in step with it automatically."
    )
    out.append("")
    for item in config["nonConsumers"]:
        out.append("- {}".format(item))
    out.append("")
    for panel in config["panels"]:
        out += render_panel(panel)
    out += render_long_press(config, {"letter"}, "letters", alphabetical=True)
    out += render_long_press(config, {"punctuation", "symbol", "space"}, "punctuation")
    return "\n".join(out).rstrip("\n") + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the manifest matches the config; write nothing",
    )
    args = parser.parse_args()

    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    generated = build(config)

    if args.check:
        current = MANIFEST.read_text(encoding="utf-8") if MANIFEST.exists() else ""
        if current != generated:
            print(
                "key-manifest.md is out of date with key-layout.json. "
                "Run: python scripts/generate-key-manifest.py",
                file=sys.stderr,
            )
            return 1
        print("key-manifest.md is up to date.")
        return 0

    MANIFEST.write_text(generated, encoding="utf-8", newline="\n")
    print("Wrote {}".format(MANIFEST.relative_to(ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
